#!/bin/bash
# Export the archive as a signed App Store .ipa.
#
#   Tools/release/export.sh                # write ExportOptions.plist, then -exportArchive
#   Tools/release/export.sh --validate     # write + lint the options plist and stop
#
# The options plist is generated, not committed: it carries the Team ID, which is
# account-specific. `--validate` is the dry run — it produces the exact plist
# `xcodebuild -exportArchive` will be handed and checks it against xcodebuild's own
# schema, so the options are proven correct before a 10-minute archive exists.
#
# Input:  .build/release/ScrollTheQuran.xcarchive   (Tools/release/archive.sh)
# Output: .build/release/export/ScrollTheQuran.ipa
# Next:   Tools/release/upload.sh

# shellcheck source=lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

VALIDATE_ONLY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --validate) VALIDATE_ONLY=1; shift ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) die "unknown argument '$1'" 2 ;;
  esac
done

cd "$RELEASE_ROOT"
need xcodebuild
need plutil

# 1. Signing -----------------------------------------------------------------
step "Signing"
TEAM="$(require_team "$@")" || exit $?
ok "DEVELOPMENT_TEAM = $TEAM"

# 2. Export options ----------------------------------------------------------
step "Export options"
mkdir -p "$BUILD_DIR"
cat > "$EXPORT_OPTIONS" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<!-- Generated by Tools/release/export.sh. Do not commit: it holds the Team ID. -->
	<key>method</key>
	<string>app-store-connect</string>
	<key>destination</key>
	<string>export</string>
	<key>teamID</key>
	<string>$TEAM</string>
	<key>signingStyle</key>
	<string>automatic</string>
	<!-- Upload the dSYMs so App Store Connect can symbolicate crash reports. -->
	<key>uploadSymbols</key>
	<true/>
	<!-- The repository owns the version numbers (Config/Release.xcconfig), not ASC. -->
	<key>manageAppVersionAndBuildNumber</key>
	<false/>
	<key>stripSwiftSymbols</key>
	<true/>
	<key>generateAppStoreInformation</key>
	<true/>
</dict>
</plist>
PLIST
plutil -lint "$EXPORT_OPTIONS" >/dev/null || die "generated ExportOptions.plist is not a valid plist"
ok "wrote $EXPORT_OPTIONS"

# xcodebuild validates the keys and their values against its own schema and exits
# non-zero on an unknown key or a bad enum value, without touching an archive.
step "Validate the options against xcodebuild's schema"
HELP="$(xcodebuild -help 2>/dev/null)"
for key in method destination teamID signingStyle uploadSymbols manageAppVersionAndBuildNumber stripSwiftSymbols generateAppStoreInformation; do
  printf '%s\n' "$HELP" | grep -q "^[[:space:]]*$key : " \
    || die "xcodebuild does not know the export option '$key' — check Xcode's -exportOptionsPlist help"
done
printf '%s\n' "$HELP" | grep -q "app-store-connect" \
  || die "this Xcode does not accept method 'app-store-connect' (older Xcode used 'app-store')"
ok "every key and the 'app-store-connect' method are accepted by this Xcode"

if [ "$VALIDATE_ONLY" -eq 1 ]; then
  plutil -p "$EXPORT_OPTIONS"
  printf '\n\033[32m==> export options validated\033[0m — run without --validate to export.\n'
  exit 0
fi

# 3. Export ------------------------------------------------------------------
step "Export"
[ -d "$ARCHIVE_PATH" ] || die "no archive at $ARCHIVE_PATH — run Tools/release/archive.sh first"
rm -rf "$EXPORT_DIR"
set -o pipefail
xcodebuild -exportArchive \
  -archivePath "$ARCHIVE_PATH" \
  -exportOptionsPlist "$EXPORT_OPTIONS" \
  -exportPath "$EXPORT_DIR" \
  -allowProvisioningUpdates 2>&1 | beautify | tail -20 || die "xcodebuild -exportArchive"
set +o pipefail

IPA="$(find "$EXPORT_DIR" -name '*.ipa' -maxdepth 1 | head -1)"
[ -n "$IPA" ] || die "no .ipa in $EXPORT_DIR"
ok "$IPA ($(du -h "$IPA" | awk '{print $1}'))"

printf '\n\033[32m==> export PASS\033[0m — next: Tools/release/upload.sh\n'
