// The reflection catalogue: every saying a REFLECTION card in the Discover feed may print.
//
// The editorial rules are `docs/content/reflections.md`, and `build-reflections.mjs` enforces
// the countable ones. In short:
//
//   * Never invent, never misattribute. Every entry names a work someone can open.
//   * `text` is **our own rendering**, made short. No published translation is copied, so
//     `translator` is always "own" and the build script writes it rather than this file.
//   * English only: "God" and never the Arabic name, no transliteration in parentheses, no
//     ruling language, no sect or school named, 10-45 words. An Arabic term central to the
//     saying may go in `arabic`, in Arabic script, for the muted line the card may draw.
//   * `attribution` is exactly what the card prints under the quote. Hadith print
//     "The Prophet Muhammad (peace be upon him)"; everyone else gets a common English name.
//   * `confidence` is about **placement**: "high" means the saying can be found in the cited
//     work by someone checking. Only "high" ships; "medium" waits here for the owner.
//
// Hadith qudsi stay in the HADITH class and keep the Prophet's attribution: he reports them.
// Quranic verses are never reflections — the feed already carries the Quran.

/** A hadith of the Prophet, from Bukhari, Muslim, Riyad al-Salihin or al-Arba'in al-Nawawiyya. */
export const HADITH = "hadith";
/** A Companion or one of the early generations, via a named classical work. */
export const EARLY = "early";
/** A classical scholar or sage, via a named work. */
export const CLASSICAL = "classical";

const PROPHET = "The Prophet Muhammad (peace be upon him)";
const BUKHARI = "Sahih al-Bukhari";
const MUSLIM = "Sahih Muslim";
const NAWAWI_40 = "Al-Arba'in al-Nawawiyya";
const RIYAD = "Riyad al-Salihin";
const NAHJ = "Nahj al-Balagha";
const HILYA = "Abu Nu'aym, Hilyat al-Awliya";
const IHYA = "Al-Ghazali, Ihya Ulum al-Din";
const AYYUHA = "Al-Ghazali, Ayyuha al-Walad";
const HIKAM = "Ibn Ata'illah, al-Hikam";
const MADARIJ = "Ibn al-Qayyim, Madarij al-Salikin";
const FAWAID = "Ibn al-Qayyim, al-Fawa'id";
const MASNAVI = "Rumi, Masnavi";
const FIHI = "Rumi, Fihi Ma Fihi";
const TADHKIRA = "Attar, Tadhkirat al-Awliya";
const SIRA = "Ibn Hisham, al-Sira al-Nabawiyya";
const JAMI = "Ibn Rajab, Jami al-Ulum wa'l-Hikam";
const AKHLAQ = "Ibn Hazm, al-Akhlaq wa'l-Siyar";
const ZUHD = "Ibn al-Mubarak, Kitab al-Zuhd";
const SIRAT_UMAR = "Ibn al-Jawzi, Sirat Umar ibn Abd al-Aziz";

/** Shorthand for the commonest row: a hadith, attributed to the Prophet, confidence high. */
const hadith = (id, work, locator, text, themes, extra = {}) => ({
    id,
    text,
    attribution: PROPHET,
    class: HADITH,
    source: { work, locator },
    themes,
    confidence: "high",
    ...extra,
});

export const reflections = [
    // ── Hadith ────────────────────────────────────────────────────────────────────────
    hadith(
        "bukhari-1-intentions", BUKHARI, "1",
        "Actions are only by intentions, and every person shall have only what he intended.",
        ["sincerity", "worship-and-devotion", "the-heart"],
        { arabic: "نية" },
    ),
    hadith(
        "bukhari-13-love-for-brother", BUKHARI, "13",
        "None of you believes until he loves for his brother what he loves for himself.",
        ["community-and-brotherhood", "good-character"],
    ),
    hadith(
        "bukhari-6018-speak-or-silent", BUKHARI, "6018",
        "Whoever believes in God and the Last Day, let him speak well or keep silent; and let him be generous to his neighbour, and generous to his guest.",
        ["speech-and-the-tongue", "good-character", "community-and-brotherhood"],
    ),
    hadith(
        "muslim-2699-relieve", MUSLIM, "2699",
        "Whoever lifts from a believer one of the burdens of this world, God lifts from him a burden on the Day of Resurrection. God helps a servant as long as the servant helps his brother.",
        ["community-and-brotherhood", "mercy-of-god", "the-day-of-judgement", "charity"],
    ),
    hadith(
        "muslim-2699-road-to-knowledge", MUSLIM, "2699",
        "Whoever travels a road in search of knowledge, God makes easy for him by it a road to the Garden.",
        ["knowledge", "paradise", "guidance"],
    ),
    hadith(
        "muslim-2999-wondrous", MUSLIM, "2999",
        "Wondrous is the affair of the believer: every part of it is good. If ease comes he gives thanks, and that is good for him; if hardship comes he is patient, and that is good for him.",
        ["patience-in-trials", "gratitude", "contentment", "hope"],
    ),
    hadith(
        "bukhari-6502-drawing-near", BUKHARI, "6502",
        "God says: My servant keeps drawing near to Me with what is beyond the obligation until I love him; and when I love him, I am the hearing with which he hears.",
        ["love-of-god", "worship-and-devotion", "divine-attributes"],
    ),
    hadith(
        "muslim-2675-as-my-servant-thinks", MUSLIM, "2675",
        "God says: I am as My servant thinks of Me, and I am with him when he remembers Me. If he remembers Me within himself, I remember him within Myself.",
        ["remembrance-of-god", "hope", "love-of-god", "divine-attributes"],
    ),
    hadith(
        "muslim-2577-injustice", MUSLIM, "2577",
        "God says: My servants, I have placed injustice out of bounds for Myself and out of bounds between you. So do not wrong one another.",
        ["justice", "divine-attributes", "community-and-brotherhood"],
    ),
    hadith(
        "muslim-2749-if-you-did-not-sin", MUSLIM, "2749",
        "If you did not sin, God would take you away and bring a people who sin and then ask forgiveness, and He would forgive them.",
        ["repentance", "forgiveness", "mercy-of-god"],
    ),
    hadith(
        "bukhari-6309-lost-camel", BUKHARI, "6309",
        "God is more delighted by the repentance of His servant than a man who lost his camel in an empty land and then found it standing in front of him.",
        ["repentance", "hope", "mercy-of-god"],
    ),
    hadith(
        "bukhari-5999-hundred-parts", BUKHARI, "5999",
        "God made mercy in a hundred parts. He kept ninety-nine with Him and sent down one, and by that one part every creature shows mercy to another.",
        ["mercy-of-god", "divine-attributes", "creation"],
    ),
    hadith(
        "muslim-2594-gentleness-adorns", MUSLIM, "2594",
        "Gentleness is never in a thing without adorning it, and is never taken out of a thing without leaving it disgraced.",
        ["good-character", "community-and-brotherhood"],
        { arabic: "رفق" },
    ),
    hadith(
        "muslim-2593-god-is-gentle", MUSLIM, "2593",
        "God is gentle and loves gentleness, and He gives for gentleness what He does not give for harshness.",
        ["good-character", "love-of-god", "divine-attributes"],
    ),
    hadith(
        "bukhari-6114-anger", BUKHARI, "6114",
        "The strong man is not the one who throws people down. The strong man is the one who holds himself in when he is angry.",
        ["good-character", "the-heart"],
    ),
    hadith(
        "bukhari-5971-your-mother", BUKHARI, "5971",
        "A man asked who most deserved his good company. He said: your mother. Then who? Your mother. Then who? Your mother. Then who? Your father.",
        ["family-and-parents", "good-character"],
    ),
    hadith(
        "muslim-2586-one-body", MUSLIM, "2586",
        "The believers, in their love and mercy and kindness towards one another, are like one body: when a limb complains, the whole body answers it with sleeplessness and fever.",
        ["community-and-brotherhood", "mercy-of-god"],
    ),
    hadith(
        "muslim-2580-conceal", MUSLIM, "2580",
        "A Muslim is the brother of a Muslim: he does not wrong him and does not abandon him. Whoever covers the fault of another, God covers his fault on the Day of Resurrection.",
        ["community-and-brotherhood", "forgiveness", "the-day-of-judgement"],
    ),
    hadith(
        "bukhari-1423-seven-in-shade", BUKHARI, "1423",
        "Seven God shelters in His shade on a day when there is no shade but His: among them a ruler who is just, a young person raised in worship, and a heart tied to the house of prayer.",
        ["justice", "worship-and-devotion", "the-day-of-judgement", "the-heart"],
    ),
    hadith(
        "bukhari-1417-half-a-date", BUKHARI, "1417",
        "Shield yourselves from the Fire, even with half a date; and whoever does not have that, then with a good word.",
        ["charity", "greed-and-generosity", "speech-and-the-tongue"],
    ),
    hadith(
        "bukhari-1442-two-angels", BUKHARI, "1442",
        "Every morning two angels come down. One says: God, give the one who spends a replacement. The other says: God, give the one who holds back ruin.",
        ["angels", "charity", "greed-and-generosity", "provision-and-sustenance"],
    ),
    hadith(
        "muslim-2588-charity-does-not-lessen", MUSLIM, "2588",
        "Charity does not make wealth less. God adds honour to a servant who pardons. And no one lowers himself for God except that God raises him.",
        ["charity", "forgiveness", "humility", "wealth-and-property"],
    ),
    hadith(
        "bukhari-6446-richness", BUKHARI, "6446",
        "Richness is not having many possessions. Richness is the richness of the soul.",
        ["contentment", "wealth-and-property", "the-heart"],
    ),
    hadith(
        "muslim-2963-look-below", MUSLIM, "2963",
        "Look at those who have less than you and do not look at those who have more. That way you are less likely to think little of what God has given you.",
        ["gratitude", "contentment", "humility"],
    ),
    hadith(
        "bukhari-6416-stranger", BUKHARI, "6416",
        "Be in this world as though you were a stranger in it, or someone crossing a road.",
        ["time-and-life", "death-and-the-hereafter", "purpose-of-life"],
    ),
    hadith(
        "muslim-2664-strive", MUSLIM, "2664",
        "Strive for what benefits you, ask God for help, and do not give up. The strong believer is better and dearer to God than the weak believer, and in both of them there is good.",
        ["trust-in-god", "hope", "worship-and-devotion"],
    ),
    hadith(
        "nawawi-19-be-mindful", NAWAWI_40, "19",
        "Be mindful of God and He will keep you. Be mindful of God and you will find Him in front of you. If you ask, ask God; if you seek help, seek it from God.",
        ["trust-in-god", "protection-and-refuge", "guidance", "supplication"],
    ),
    hadith(
        "nawawi-18-follow-with-good", NAWAWI_40, "18",
        "Be mindful of God wherever you are. Follow a bad deed with a good one and it will wipe it out. And meet people with good character.",
        ["good-character", "repentance", "sincerity"],
    ),
    hadith(
        "nawawi-11-leave-doubt", NAWAWI_40, "11",
        "Leave what makes you doubt for what does not make you doubt.",
        ["honesty-and-truthfulness", "the-heart", "sincerity"],
    ),
    hadith(
        "nawawi-12-what-does-not-concern", NAWAWI_40, "12",
        "Part of a person's excellence in faith is leaving alone what does not concern him.",
        ["speech-and-the-tongue", "good-character"],
    ),
    hadith(
        "bukhari-52-piece-of-flesh", BUKHARI, "52",
        "In the body there is a piece of flesh: when it is sound the whole body is sound, and when it is spoiled the whole body is spoiled. It is the heart.",
        ["the-heart", "sincerity"],
        { arabic: "قلب" },
    ),
    hadith(
        "muslim-2564-looks-at-hearts", MUSLIM, "2564",
        "God does not look at your bodies or at your forms. He looks at your hearts and at your deeds.",
        ["the-heart", "sincerity", "humility"],
    ),
    hadith(
        "muslim-2581-bankrupt", MUSLIM, "2581",
        "The bankrupt of my community is the one who arrives with prayer and fasting and charity, but who insulted this one, struck that one, and took what belonged to another.",
        ["justice", "the-day-of-judgement", "speech-and-the-tongue"],
    ),
    hadith(
        "bukhari-6474-jaws", BUKHARI, "6474",
        "Whoever guarantees me what is between his jaws and what is between his legs, I guarantee him the Garden.",
        ["speech-and-the-tongue", "paradise", "good-character"],
    ),
    hadith(
        "bukhari-5027-learn-and-teach", BUKHARI, "5027",
        "The best of you are those who learn the Quran and teach it.",
        ["the-quran", "knowledge"],
    ),
    hadith(
        "muslim-804-intercessor", MUSLIM, "804",
        "Recite the Quran, for it comes on the Day of Resurrection speaking for those who kept its company.",
        ["the-quran", "the-day-of-judgement"],
    ),
    hadith(
        "bukhari-5020-citron", BUKHARI, "5020",
        "The believer who recites the Quran is like a citron: its scent is sweet and its taste is sweet.",
        ["the-quran", "good-character"],
    ),
    hadith(
        "bukhari-4937-stumbles", BUKHARI, "4937",
        "One who is at home in the Quran is with the noble recording angels; one who stumbles over it and finds it hard has two rewards.",
        ["the-quran", "angels", "knowledge"],
    ),
    hadith(
        "bukhari-71-understanding", BUKHARI, "71",
        "When God wants good for someone, He gives him understanding in religion.",
        ["knowledge", "guidance"],
    ),
    hadith(
        "bukhari-79-rain-on-land", BUKHARI, "79",
        "What God sent me with is like rain falling on land. Some ground drank and grew; some held the water so people could drink; and some was flat and kept nothing.",
        ["rain-and-the-earth", "knowledge", "guidance", "revelation-and-its-rejection"],
    ),
    hadith(
        "bukhari-6407-living-and-dead", BUKHARI, "6407",
        "The likeness of one who remembers his Lord and one who does not is the likeness of the living and the dead.",
        ["remembrance-of-god", "the-heart"],
        { arabic: "ذكر" },
    ),
    hadith(
        "muslim-2691-hundred-times", MUSLIM, "2691",
        "Whoever says, glory to God and praise to Him, a hundred times in a day has his wrongs wiped away, though they were like the foam of the sea.",
        ["remembrance-of-god", "forgiveness"],
    ),
    hadith(
        "muslim-2689-gathering", MUSLIM, "2689",
        "No people gather to remember God without the angels surrounding them, mercy covering them, stillness coming down on them, and God mentioning them to those who are with Him.",
        ["remembrance-of-god", "angels", "community-and-brotherhood"],
    ),
    hadith(
        "bukhari-1145-last-third", BUKHARI, "1145",
        "Our Lord comes down each night to the lowest heaven when the last third of the night is left, and says: who is calling on Me, that I may answer him?",
        ["supplication", "night-and-day", "mercy-of-god"],
    ),
    hadith(
        "muslim-482-prostrating", MUSLIM, "482",
        "The closest a servant comes to his Lord is while he is prostrating, so ask much of Him then.",
        ["prayer", "supplication", "humility"],
    ),
    hadith(
        "bukhari-528-river-at-your-door", BUKHARI, "528",
        "If a river ran at your door and you washed in it five times a day, would any dirt be left on you? So it is with the five prayers: God wipes away wrongdoing with them.",
        ["prayer", "forgiveness", "worship-and-devotion"],
    ),
    hadith(
        "muslim-223-prayer-is-light", MUSLIM, "223",
        "Prayer is light, charity is proof, patience is a brightness, and the Quran is an argument for you or against you.",
        ["light", "prayer", "charity", "patience-in-trials", "the-quran"],
    ),
    hadith(
        "bukhari-6316-light-in-my-heart", BUKHARI, "6316",
        "God, put light in my heart, light in my hearing, light in my sight, light on my right and light on my left, and make me light.",
        ["light", "supplication", "guidance", "the-heart"],
    ),
    hadith(
        "muslim-veil-of-light", MUSLIM, "the Book of Faith",
        "His veil is light. Were He to draw it back, the splendours of His face would burn away everything His sight reached.",
        ["light", "divine-attributes"],
    ),
    hadith(
        "muslim-1151-fasting-is-mine", MUSLIM, "1151",
        "God says: every deed of the child of Adam belongs to him, except fasting. That is Mine, and I am the one who rewards it.",
        ["ramadan-and-fasting", "sincerity", "worship-and-devotion"],
    ),
    hadith(
        "muslim-1079-ramadan-gates", MUSLIM, "1079",
        "When Ramadan comes, the gates of mercy are opened, the gates of the Fire are shut, and the devils are put in chains.",
        ["ramadan-and-fasting", "mercy-of-god", "protection-and-refuge"],
    ),
    hadith(
        "muslim-1163-night-prayer", MUSLIM, "1163",
        "The best fasting after the month of Ramadan is in the month of God, and the best prayer after what is prescribed is the prayer of the night.",
        ["night-and-day", "prayer", "ramadan-and-fasting", "worship-and-devotion"],
    ),
    hadith(
        "bukhari-1131-prayer-of-david", BUKHARI, "1131",
        "The prayer dearest to God is the prayer of David: he slept half the night, stood a third of it, and slept a sixth.",
        ["night-and-day", "solomon-and-david", "worship-and-devotion", "prayer"],
    ),
    hadith(
        "bukhari-1976-fast-of-david", BUKHARI, "1976",
        "The fasting dearest to God is the fasting of David: he fasted one day and ate the next.",
        ["solomon-and-david", "ramadan-and-fasting", "worship-and-devotion"],
    ),
    hadith(
        "bukhari-555-angels-take-turns", BUKHARI, "555",
        "Angels take turns among you, by night and by day, and they gather at the dawn prayer and at the afternoon prayer.",
        ["angels", "night-and-day", "prayer"],
    ),
    hadith(
        "bukhari-1521-pilgrimage-newborn", BUKHARI, "1521",
        "Whoever makes the pilgrimage and speaks no obscenity and does no wrong comes back as on the day his mother bore him.",
        ["pilgrimage", "forgiveness", "repentance"],
    ),
    hadith(
        "muslim-1349-one-pilgrimage", MUSLIM, "1349",
        "One pilgrimage to the next wipes out what lies between them, and a pilgrimage that is accepted has no reward but the Garden.",
        ["pilgrimage", "paradise", "forgiveness"],
    ),
    hadith(
        "bukhari-3364-hagar", BUKHARI, "3364",
        "Hagar called after Abraham as he left her in the empty valley: did God command you this? He said yes. She said: then He will not abandon us.",
        ["abraham", "trust-in-god", "provision-and-sustenance", "pilgrimage"],
    ),
    hadith(
        "bukhari-noble-son", BUKHARI, "the Book of the Stories of the Prophets",
        "The noble son of the noble son of the noble son of the noble: Joseph, son of Jacob, son of Isaac, son of Abraham.",
        ["joseph", "abraham", "prophets", "family-and-parents"],
    ),
    hadith(
        "bukhari-joseph-in-prison", BUKHARI, "the Book of the Stories of the Prophets",
        "We have more right to doubt than Abraham had. And had I stayed in prison as long as Joseph stayed, I would have answered the messenger at once.",
        ["joseph", "abraham", "patience-in-trials", "prophets"],
    ),
    hadith(
        "muslim-194-they-go-to-adam", MUSLIM, "194",
        "On that day people will go to Adam, and he will send them to Noah, and Noah to Abraham, and Abraham to Moses, and Moses to Jesus, and Jesus will send them on.",
        ["the-day-of-judgement", "prophets", "adam-and-the-human-story", "noah", "abraham", "moses", "jesus-son-of-mary"],
    ),
    hadith(
        "muslim-194-noah-first-messenger", MUSLIM, "194",
        "They will come to Noah and say to him: you are the first messenger God sent to the people of the earth.",
        ["noah", "prophets", "revelation-and-its-rejection"],
    ),
    hadith(
        "bukhari-noah-questioned", BUKHARI, "the Book of the Stories of the Prophets",
        "Noah will be called and asked whether he delivered the message, and he will say yes. His people will be asked, and they will say: no warner ever came to us.",
        ["noah", "revelation-and-its-rejection", "the-day-of-judgement"],
    ),
    hadith(
        "bukhari-3435-word-given-to-mary", BUKHARI, "3435",
        "Whoever bears witness that there is no god but God alone, and that Jesus is God's servant and His messenger, His word given to Mary and a spirit from Him, God brings into the Garden.",
        ["jesus-son-of-mary", "mary", "paradise", "prophets"],
    ),
    hadith(
        "bukhari-3442-nearest-to-jesus", BUKHARI, "3442",
        "I am the nearest of people to Jesus, son of Mary, in this world and the next. The prophets are brothers: one father, different mothers, and one religion.",
        ["jesus-son-of-mary", "prophets"],
    ),
    hadith(
        "bukhari-mary-and-asiya", BUKHARI, "the Book of the Stories of the Prophets",
        "Many men have reached completeness, but among women none has except Mary the daughter of Imran and Asiya the wife of Pharaoh.",
        ["mary", "good-character", "prophets"],
    ),
    hadith(
        "muslim-2366-except-mary", MUSLIM, "2366",
        "Every child of Adam is touched by Satan at the moment of birth and cries out from that touch, except Mary and her son.",
        ["mary", "jesus-son-of-mary", "adam-and-the-human-story", "protection-and-refuge"],
    ),
    hadith(
        "bukhari-3401-moses-and-knowledge", BUKHARI, "3401",
        "Moses was asked who among people knew the most, and he said: I do. God corrected him for not handing the knowledge back to Him, and sent him to a servant who knew what he did not.",
        ["moses", "knowledge", "humility", "prophets"],
    ),
    hadith(
        "muslim-2380-bird-and-the-sea", MUSLIM, "2380",
        "Khidr said to Moses: my knowledge and yours take from the knowledge of God no more than this bird has taken from the sea with its beak.",
        ["moses", "knowledge", "humility"],
    ),
    hadith(
        "bukhari-solomon-if-god-wills", BUKHARI, "the Book of the Stories of the Prophets",
        "Solomon said: tonight I will go to my wives, and each will bear a horseman who fights for God. His companion said, say if God wills. He did not, and only one child was born.",
        ["solomon-and-david", "trust-in-god", "prophets"],
    ),
    hadith(
        "bukhari-solomon-and-the-child", BUKHARI, "the Book of the Stories of the Prophets",
        "Two women lost a child to a wolf. David judged for the elder. Solomon called for a knife to divide the boy between them, and the younger cried out, so he gave the child to her.",
        ["solomon-and-david", "justice", "knowledge", "family-and-parents"],
    ),
    hadith(
        "muslim-2996-angels-from-light", MUSLIM, "2996",
        "The angels were created from light, the jinn from a smokeless fire, and Adam from what has been described to you.",
        ["angels", "creation", "adam-and-the-human-story", "light"],
    ),
    hadith(
        "muslim-2643-in-the-womb", MUSLIM, "2643",
        "Each of you is gathered in his mother's womb, and then an angel is sent and told four things: his provision, the length of his life, what he will do, and whether he will be fortunate.",
        ["creation", "angels", "provision-and-sustenance"],
    ),
    hadith(
        "bukhari-7422-mercy-over-wrath", BUKHARI, "7422",
        "When God decreed creation He wrote in a book kept with Him above the Throne: My mercy overcomes My anger.",
        ["creation", "mercy-of-god", "divine-attributes"],
    ),
    hadith(
        "bukhari-2736-ninety-nine-names", BUKHARI, "2736",
        "God has ninety-nine names, one short of a hundred. Whoever takes them in and lives by them enters the Garden.",
        ["divine-attributes", "paradise"],
    ),
    hadith(
        "muslim-2708-perfect-words", MUSLIM, "2708",
        "Whoever stops somewhere and says, I take refuge in the perfect words of God from the evil of what He made, nothing will harm him until he moves on.",
        ["protection-and-refuge", "supplication"],
    ),
    hadith(
        "bukhari-2311-throne-verse", BUKHARI, "2311",
        "Whoever recites the Throne Verse when he goes to bed will have a guardian from God, and nothing evil will come near him until morning.",
        ["protection-and-refuge", "the-quran", "angels", "night-and-day"],
    ),
    hadith(
        "muslim-2706-refuge-from-idleness", MUSLIM, "2706",
        "God, I take refuge in You from helplessness and idleness, from cowardice and miserliness, from the weight of debt and from being overpowered by other men.",
        ["supplication", "protection-and-refuge", "greed-and-generosity"],
    ),
    hadith(
        "muslim-2877-think-well-of-god", MUSLIM, "2877",
        "Let none of you die except while thinking well of God.",
        ["fear-and-hope", "hope", "death-and-the-hereafter"],
    ),
    hadith(
        "muslim-2755-if-the-believer-knew", MUSLIM, "2755",
        "If the believer knew what punishment is with God, no one would hope for His Garden; and if the one who denies knew what mercy is with God, no one would despair of it.",
        ["fear-and-hope", "mercy-of-god", "hope"],
    ),
    hadith(
        "bukhari-6514-three-follow", BUKHARI, "6514",
        "Three things follow a man to the grave. Two come back and one stays. His family and his wealth come back; what he did stays with him.",
        ["death-and-the-hereafter", "wealth-and-property", "time-and-life"],
    ),
    hadith(
        "muslim-2858-finger-in-the-sea", MUSLIM, "2858",
        "What is this world beside the next but as if one of you dipped a finger in the sea? Let him look at what comes back on it.",
        ["purpose-of-life", "death-and-the-hereafter", "time-and-life"],
    ),
    hadith(
        "bukhari-6412-two-blessings", BUKHARI, "6412",
        "Two blessings that many people are cheated of: good health, and free time.",
        ["time-and-life", "gratitude", "purpose-of-life"],
    ),
    hadith(
        "bukhari-6464-steady-deeds", BUKHARI, "6464",
        "Take on what you can keep up, for God does not tire until you tire; and the deeds dearest to God are the steady ones, even when they are few.",
        ["worship-and-devotion", "contentment"],
    ),
    hadith(
        "muslim-2819-grateful-servant", MUSLIM, "2819",
        "Should I not be a servant who gives thanks? So he answered when he was asked why he stood in prayer until his feet swelled.",
        ["gratitude", "prayer", "worship-and-devotion"],
    ),
    hadith(
        "muslim-71-rain-by-gods-favour", MUSLIM, "71",
        "God says: this morning some of My servants believed in Me and some denied Me. Whoever said, we were given rain by God's favour, believed in Me.",
        ["rain-and-the-earth", "gratitude", "provision-and-sustenance"],
    ),
    hadith(
        "bukhari-1032-rain-that-gives-life", BUKHARI, "1032",
        "God, make it a rain that gives life and does good, a rain that waters and is not a punishment.",
        ["rain-and-the-earth", "supplication", "provision-and-sustenance"],
    ),
    {
        id: "ibn-abbas-more-giving-than-the-wind",
        text: "He was the most generous of people, and the most generous of all in Ramadan when the angel met him, more giving than a wind let loose.",
        attribution: "Abdullah ibn Abbas",
        class: EARLY,
        source: { work: BUKHARI, locator: "6" },
        themes: ["greed-and-generosity", "ramadan-and-fasting", "angels", "charity"],
        confidence: "high",
    },
    hadith(
        "bukhari-6094-truthfulness", BUKHARI, "6094",
        "Truthfulness leads to goodness, and goodness leads to the Garden. A man keeps telling the truth until he is written down with God as one who tells the truth.",
        ["honesty-and-truthfulness", "paradise", "good-character"],
        { arabic: "صدق" },
    ),
    hadith(
        "bukhari-33-three-signs", BUKHARI, "33",
        "Three are the signs of a false heart: when he speaks he lies, when he promises he breaks it, and when he is trusted he betrays the trust.",
        ["honesty-and-truthfulness", "speech-and-the-tongue", "the-heart"],
    ),
    hadith(
        "muslim-2958-my-wealth", MUSLIM, "2958",
        "The child of Adam says: my wealth, my wealth. But your wealth is only what you ate and used up, what you wore and wore out, and what you gave away and so kept.",
        ["wealth-and-property", "charity", "death-and-the-hereafter", "greed-and-generosity"],
    ),
    hadith(
        "muslim-2674-calls-to-guidance", MUSLIM, "2674",
        "Whoever calls people to guidance has a reward like the rewards of those who follow him, without any of theirs being made less.",
        ["guidance", "knowledge", "community-and-brotherhood"],
    ),
    hadith(
        "bukhari-7274-what-i-was-given", BUKHARI, "7274",
        "Every prophet was given signs that made people believe. What I was given is a revelation that God revealed to me.",
        ["revelation-and-its-rejection", "the-quran", "prophets"],
    ),
    hadith(
        "muslim-2567-loved-for-my-greatness", MUSLIM, "2567",
        "God says on the Day of Resurrection: where are those who loved one another for My greatness? Today I shade them in My shade, on a day when there is no shade but Mine.",
        ["love-of-god", "community-and-brotherhood", "the-day-of-judgement"],
    ),
    hadith(
        "bukhari-3244-no-eye-has-seen", BUKHARI, "3244",
        "God says: I have prepared for My upright servants what no eye has seen, no ear has heard, and no heart has ever imagined.",
        ["paradise", "hope", "the-heart"],
    ),
    hadith(
        "muslim-2551-parents-in-old-age", MUSLIM, "2551",
        "May he be brought low who finds his parents in old age, one of them or both, and does not enter the Garden through them.",
        ["family-and-parents", "paradise"],
    ),
    hadith(
        "bukhari-5997-whoever-shows-no-mercy", BUKHARI, "5997",
        "A man said he had ten children and had never kissed one of them. He said: whoever shows no mercy is shown no mercy.",
        ["family-and-parents", "mercy-of-god", "good-character"],
    ),
    hadith(
        "bukhari-5991-restores-the-tie", BUKHARI, "5991",
        "The one who keeps the ties of kinship is not the one who repays in kind. He is the one who restores the tie when it has been cut.",
        ["family-and-parents", "community-and-brotherhood", "forgiveness"],
    ),
    hadith(
        "bukhari-6035-best-in-character", BUKHARI, "6035",
        "The best of you are the best of you in character.",
        ["good-character", "community-and-brotherhood"],
        { arabic: "خلق" },
    ),
    hadith(
        "muslim-2865-be-humble", MUSLIM, "2865",
        "God has revealed to me that people are to be humble with one another, so that no one boasts over another and no one oppresses another.",
        ["humility", "community-and-brotherhood", "justice"],
    ),
    hadith(
        "bukhari-1283-first-blow", BUKHARI, "1283",
        "He came upon a woman weeping at a grave and said: be mindful of God, and be patient. Patience is at the first blow.",
        ["patience-in-trials", "death-and-the-hereafter"],
        { arabic: "صبر" },
    ),
    hadith(
        "muslim-2573-even-a-thorn", MUSLIM, "2573",
        "No weariness, illness, worry, grief, hurt or distress reaches a believer, not even a thorn that pricks him, without God wiping away some of his wrongs by it.",
        ["patience-in-trials", "forgiveness", "mercy-of-god"],
    ),
    hadith(
        "muslim-1679-sacred-as-this-day", MUSLIM, "1679",
        "Your blood and your property are sacred among you, like the sanctity of this day, in this month, in this land.",
        ["justice", "pilgrimage", "community-and-brotherhood"],
    ),
    hadith(
        "riyad-trust-like-the-birds", RIYAD, "chapter on certainty and reliance on God",
        "If you relied on God as He should be relied on, He would provide for you as He provides for the birds: they go out empty in the morning and come back full.",
        ["trust-in-god", "provision-and-sustenance", "contentment"],
        { arabic: "توكل" },
    ),
    hadith(
        "riyad-remember-the-ender", RIYAD, "chapter on the remembrance of death",
        "Remember often the one thing that cuts every pleasure short.",
        ["death-and-the-hereafter", "time-and-life", "remembrance-of-god"],
        { confidence: "medium" },
    ),

    // ── Companions and the early generations ──────────────────────────────────────────
    {
        id: "ibn-umar-do-not-expect-the-morning",
        text: "If you reach evening, do not expect the morning; if you reach morning, do not expect the evening. Take from your health for your illness, and from your life for your death.",
        attribution: "Abdullah ibn Umar",
        class: EARLY,
        source: { work: BUKHARI, locator: "6416" },
        themes: ["time-and-life", "death-and-the-hereafter", "purpose-of-life"],
        confidence: "high",
    },
    {
        id: "ali-speak-with-what-they-know",
        text: "Speak to people with what they can know. Would you want God and His Messenger to be denied?",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: BUKHARI, locator: "Book of Knowledge, before hadith 127" },
        themes: ["knowledge", "speech-and-the-tongue", "guidance"],
        confidence: "high",
    },
    {
        id: "abu-bakr-not-the-best-of-you",
        text: "I have been put in charge of you and I am not the best of you. If I do well, help me; if I go wrong, set me straight.",
        attribution: "Abu Bakr al-Siddiq",
        class: EARLY,
        source: { work: SIRA, locator: "his first address after the Prophet's death" },
        themes: ["humility", "justice", "honesty-and-truthfulness"],
        confidence: "high",
    },
    {
        id: "abu-bakr-the-weak-is-strong",
        text: "The weak among you is strong with me until I secure his right; the strong among you is weak with me until I take from him what is owed.",
        attribution: "Abu Bakr al-Siddiq",
        class: EARLY,
        source: { work: SIRA, locator: "his first address after the Prophet's death" },
        themes: ["justice", "community-and-brotherhood", "humility"],
        confidence: "high",
    },
    {
        id: "umar-call-yourselves-to-account",
        text: "Call yourselves to account before you are called to account, and weigh your deeds before they are weighed for you.",
        attribution: "Umar ibn al-Khattab",
        class: EARLY,
        source: { work: JAMI, locator: "commentary on the hadith of the stranger" },
        themes: ["death-and-the-hereafter", "the-day-of-judgement", "purpose-of-life"],
        confidence: "medium",
    },
    {
        id: "umar-shows-me-my-faults",
        text: "The dearest of people to me is the one who shows me my own faults.",
        attribution: "Umar ibn al-Khattab",
        class: EARLY,
        source: { work: HILYA, locator: "the section on Umar ibn al-Khattab" },
        themes: ["humility", "honesty-and-truthfulness", "good-character"],
        confidence: "medium",
    },
    {
        id: "uthman-if-our-hearts-were-clean",
        text: "If our hearts were clean, we would never have our fill of the words of our Lord.",
        attribution: "Uthman ibn Affan",
        class: EARLY,
        source: { work: HILYA, locator: "the section on Uthman ibn Affan" },
        themes: ["the-quran", "the-heart", "sincerity"],
        confidence: "medium",
    },
    {
        id: "ali-knowledge-guards-you",
        text: "Knowledge is better than wealth. Knowledge guards you, while you have to guard wealth. Wealth grows less when you spend it; knowledge grows more.",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: NAHJ, locator: "Short Sayings, to Kumayl ibn Ziyad" },
        themes: ["knowledge", "wealth-and-property"],
        confidence: "high",
    },
    {
        id: "ali-worth-of-every-man",
        text: "The worth of every man is the thing that he does well.",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: NAHJ, locator: "Short Sayings" },
        themes: ["good-character", "knowledge", "purpose-of-life"],
        confidence: "high",
    },
    {
        id: "ali-tongue-behind-the-heart",
        text: "The tongue of the wise man is behind his heart, and the heart of the fool is behind his tongue.",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: NAHJ, locator: "Short Sayings" },
        themes: ["speech-and-the-tongue", "the-heart", "knowledge"],
        confidence: "high",
    },
    {
        id: "ali-no-wealth-like-a-clear-mind",
        text: "There is no wealth like a clear mind, no poverty like ignorance, no inheritance like good manners, and no support like taking counsel.",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: NAHJ, locator: "Short Sayings" },
        themes: ["knowledge", "wealth-and-property", "good-character"],
        confidence: "high",
    },
    {
        id: "ali-house-of-truth",
        text: "The world is a house of truth for one who is truthful with it, a house of safety for one who understands it, and a house of wealth for one who takes provision from it.",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: NAHJ, locator: "Short Sayings" },
        themes: ["time-and-life", "purpose-of-life", "contentment", "wealth-and-property"],
        confidence: "high",
    },
    {
        id: "ali-make-yourself-a-measure",
        text: "Make yourself a measure between you and everyone else. Want for them what you want for yourself, and dislike for them what you dislike for yourself.",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: NAHJ, locator: "Letter 31, to his son al-Hasan" },
        themes: ["good-character", "justice", "community-and-brotherhood"],
        confidence: "high",
    },
    {
        id: "ali-their-speech-is-measured",
        text: "Their speech is measured, their clothing plain, their walk unhurried. They lower their eyes from what they were told not to look at, and give their ears to knowledge that helps.",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: NAHJ, locator: "Sermon 193, on those who are mindful of God" },
        themes: ["humility", "worship-and-devotion", "good-character"],
        confidence: "high",
    },
    {
        id: "ali-sets-right-what-is-between",
        text: "Whoever sets right what is between himself and God, God sets right what is between him and people.",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: NAHJ, locator: "Short Sayings" },
        themes: ["sincerity", "trust-in-god", "community-and-brotherhood"],
        confidence: "high",
    },
    {
        id: "ali-patience-is-the-head",
        text: "Patience is to faith what the head is to the body: when the head goes, the body goes after it.",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: NAHJ, locator: "Short Sayings" },
        themes: ["patience-in-trials", "the-heart"],
        arabic: "صبر",
        confidence: "high",
    },
    {
        id: "ali-world-turned-its-back",
        text: "The world has turned its back and is going; the next life has turned its face and is coming. Each of the two has children, so be among the children of the next life.",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: NAHJ, locator: "Short Sayings" },
        themes: ["death-and-the-hereafter", "purpose-of-life", "time-and-life"],
        confidence: "high",
    },
    {
        id: "hasan-number-of-days",
        text: "Son of Adam, you are only a number of days. Whenever a day goes, part of you has gone with it.",
        attribution: "Al-Hasan al-Basri",
        class: EARLY,
        source: { work: HILYA, locator: "the section on al-Hasan al-Basri" },
        themes: ["time-and-life", "death-and-the-hereafter", "adam-and-the-human-story"],
        confidence: "high",
    },
    {
        id: "hasan-good-work-and-fear",
        text: "The believer joins good work with fear, and the heedless man joins bad work with a feeling of safety.",
        attribution: "Al-Hasan al-Basri",
        class: EARLY,
        source: { work: HILYA, locator: "the section on al-Hasan al-Basri" },
        themes: ["fear-and-hope", "sincerity"],
        confidence: "medium",
    },
    {
        id: "hasan-death-has-shown-the-world",
        text: "Death has shown this world for what it is, and has left no joy in it for anyone with sense.",
        attribution: "Al-Hasan al-Basri",
        class: EARLY,
        source: { work: HILYA, locator: "the section on al-Hasan al-Basri" },
        themes: ["death-and-the-hereafter", "time-and-life"],
        confidence: "medium",
    },
    {
        id: "hasan-world-is-three-days",
        text: "The world is three days. Yesterday has gone with everything in it. Tomorrow you may never reach. Today is yours, so work in it.",
        attribution: "Al-Hasan al-Basri",
        class: EARLY,
        source: { work: HILYA, locator: "the section on al-Hasan al-Basri" },
        themes: ["time-and-life", "purpose-of-life", "night-and-day"],
        confidence: "medium",
    },
    {
        id: "ibn-al-mubarak-small-deed",
        text: "How often a small deed is made great by the intention behind it, and how often a great deed is made small by the same.",
        attribution: "Abdullah ibn al-Mubarak",
        class: EARLY,
        source: { work: JAMI, locator: "commentary on the first hadith" },
        themes: ["sincerity", "worship-and-devotion"],
        arabic: "إخلاص",
        confidence: "high",
    },
    {
        id: "umar-abd-al-aziz-without-knowledge",
        text: "Whoever acts without knowledge spoils more than he sets right.",
        attribution: "Umar ibn Abd al-Aziz",
        class: EARLY,
        source: { work: BUKHARI, locator: "Book of Knowledge, chapter headings" },
        themes: ["knowledge", "guidance"],
        confidence: "high",
    },
    {
        id: "umar-abd-al-aziz-night-and-day",
        text: "The night and the day are working on you, so do your own work in them.",
        attribution: "Umar ibn Abd al-Aziz",
        class: EARLY,
        source: { work: SIRAT_UMAR, locator: "his letters and sermons" },
        themes: ["night-and-day", "time-and-life", "purpose-of-life"],
        confidence: "medium",
    },
    {
        id: "aisha-his-character-was-the-quran",
        text: "She was asked what the Prophet's character was like, and she said: his character was the Quran.",
        attribution: "Aisha bint Abi Bakr",
        class: EARLY,
        source: { work: MUSLIM, locator: "746" },
        themes: ["the-quran", "good-character", "prophets"],
        confidence: "high",
    },
    {
        id: "ibn-abbas-god-is-enough",
        text: "God is enough for us, and He is the best to trust. Abraham said it when he was thrown into the fire, and the Prophet said it when the armies gathered against him.",
        attribution: "Abdullah ibn Abbas",
        class: EARLY,
        source: { work: BUKHARI, locator: "4563" },
        themes: ["trust-in-god", "abraham", "protection-and-refuge"],
        confidence: "high",
    },
    {
        id: "salman-every-right-its-due",
        text: "Your Lord has a right over you, your body has a right over you, and your family has a right over you. Give every one of them its due.",
        attribution: "Salman al-Farisi",
        class: EARLY,
        source: { work: BUKHARI, locator: "1968" },
        themes: ["family-and-parents", "contentment", "worship-and-devotion"],
        confidence: "high",
    },
    {
        id: "fudayl-sincerity-frees-you",
        text: "Leaving a deed for the sake of people is showing off; doing a deed for the sake of people is setting up a partner. Sincerity is that God frees you from both.",
        attribution: "Al-Fudayl ibn Iyad",
        class: EARLY,
        source: { work: IHYA, locator: "the Book of Sincerity and Truthfulness" },
        themes: ["sincerity", "worship-and-devotion", "the-heart"],
        confidence: "high",
    },
    {
        id: "sufyan-my-own-intention",
        text: "I have never had to treat anything harder than my own intention, because it keeps turning on me.",
        attribution: "Sufyan al-Thawri",
        class: EARLY,
        source: { work: HILYA, locator: "the section on Sufyan al-Thawri" },
        themes: ["sincerity", "the-heart"],
        confidence: "medium",
    },
    {
        id: "malik-ibn-dinar-heedless-company",
        text: "I have found nothing harder on the heart than sitting with people who have stopped paying attention.",
        attribution: "Malik ibn Dinar",
        class: EARLY,
        source: { work: HILYA, locator: "the section on Malik ibn Dinar" },
        themes: ["the-heart", "community-and-brotherhood", "remembrance-of-god"],
        confidence: "medium",
    },
    {
        id: "ibrahim-ibn-adham-kings-would-fight",
        text: "We are in a happiness that, if kings and their sons knew of it, they would fight us for it with swords.",
        attribution: "Ibrahim ibn Adham",
        class: EARLY,
        source: { work: HILYA, locator: "the section on Ibrahim ibn Adham" },
        themes: ["contentment", "wealth-and-property", "love-of-god"],
        confidence: "medium",
    },
    {
        id: "wuhayb-be-someone-nobody-knows",
        text: "If you are able to be someone whom nobody knows, then be him.",
        attribution: "Wuhayb ibn al-Ward",
        class: EARLY,
        source: { work: HILYA, locator: "the section on Wuhayb ibn al-Ward" },
        themes: ["sincerity", "humility"],
        confidence: "medium",
    },
    {
        id: "ibn-masud-a-day-whose-sun-went-down",
        text: "I have regretted nothing so much as a day whose sun went down with my life shortened by it and my deeds not increased.",
        attribution: "Abdullah ibn Mas'ud",
        class: EARLY,
        source: { work: ZUHD, locator: "the chapter on guarding one's days" },
        themes: ["time-and-life", "purpose-of-life", "night-and-day"],
        confidence: "medium",
    },
    {
        id: "abu-darda-three-things",
        text: "I love death, out of longing for my Lord; and illness, as a washing of what I have done; and poverty, as lowliness before Him.",
        attribution: "Abu al-Darda",
        class: EARLY,
        source: { work: HILYA, locator: "the section on Abu al-Darda" },
        themes: ["death-and-the-hereafter", "humility", "love-of-god"],
        confidence: "medium",
    },

    // ── Classical scholars and sages ──────────────────────────────────────────────────
    {
        id: "hikam-signs-of-relying-on-works",
        text: "Among the signs of leaning on your own works is that hope grows weak in you the moment you slip.",
        attribution: "Ibn Ata'illah",
        class: CLASSICAL,
        source: { work: HIKAM, locator: "Aphorism 1" },
        themes: ["trust-in-god", "hope", "sincerity", "repentance"],
        confidence: "high",
    },
    {
        id: "hikam-wanting-to-withdraw",
        text: "Your wanting to withdraw when God has placed you among people is a quiet appetite; your wanting to be among people when He has withdrawn you is a fall from high aim.",
        attribution: "Ibn Ata'illah",
        class: CLASSICAL,
        source: { work: HIKAM, locator: "Aphorism 2" },
        themes: ["contentment", "sincerity", "purpose-of-life"],
        confidence: "high",
    },
    {
        id: "hikam-rest-from-managing",
        text: "Rest yourself from running your own affairs. What Another has already taken care of for you, do not take up yourself.",
        attribution: "Ibn Ata'illah",
        class: CLASSICAL,
        source: { work: HIKAM, locator: "Aphorisms" },
        themes: ["trust-in-god", "contentment", "provision-and-sustenance"],
        confidence: "high",
    },
    {
        id: "hikam-delayed-gift",
        text: "Do not let a gift withheld, after you have asked and asked again, make you lose heart. He has promised an answer in what He chooses for you, not in what you choose, and at the time He wants.",
        attribution: "Ibn Ata'illah",
        class: CLASSICAL,
        source: { work: HIKAM, locator: "Aphorisms" },
        themes: ["supplication", "trust-in-god", "hope", "patience-in-trials"],
        confidence: "high",
    },
    {
        id: "hikam-bury-your-existence",
        text: "Bury your existence in the ground of obscurity. Whatever sprouts before it has been buried comes to nothing.",
        attribution: "Ibn Ata'illah",
        class: CLASSICAL,
        source: { work: HIKAM, locator: "Aphorisms" },
        themes: ["humility", "sincerity"],
        confidence: "high",
    },
    {
        id: "hikam-a-wrong-that-humbles",
        text: "A wrong that leaves you humbled and in need is better than an act of obedience that leaves you proud and pleased with yourself.",
        attribution: "Ibn Ata'illah",
        class: CLASSICAL,
        source: { work: HIKAM, locator: "Aphorisms" },
        themes: ["humility", "repentance", "sincerity"],
        confidence: "high",
    },
    {
        id: "hikam-mirror-of-the-heart",
        text: "How is the heart to be lit up while the shapes of created things are printed on its mirror?",
        attribution: "Ibn Ata'illah",
        class: CLASSICAL,
        source: { work: HIKAM, locator: "Aphorisms" },
        themes: ["the-heart", "light", "remembrance-of-god"],
        confidence: "high",
    },
    {
        id: "hikam-gives-while-withholding",
        text: "Sometimes He gives you while withholding from you, and sometimes He withholds from you while giving to you.",
        attribution: "Ibn Ata'illah",
        class: CLASSICAL,
        source: { work: HIKAM, locator: "Aphorisms" },
        themes: ["provision-and-sustenance", "contentment", "trust-in-god"],
        confidence: "high",
    },
    {
        id: "hikam-nothing-is-hard",
        text: "Nothing you look for leaning on your Lord is hard, and nothing you look for leaning on yourself is easy.",
        attribution: "Ibn Ata'illah",
        class: CLASSICAL,
        source: { work: HIKAM, locator: "Aphorisms" },
        themes: ["trust-in-god", "supplication", "hope"],
        confidence: "high",
    },
    {
        id: "hikam-best-of-your-moments",
        text: "The best of your moments is the one in which you see your own poverty, and are handed back to your own lowliness.",
        attribution: "Ibn Ata'illah",
        class: CLASSICAL,
        source: { work: HIKAM, locator: "Aphorisms" },
        themes: ["humility", "the-heart", "supplication"],
        confidence: "high",
    },
    {
        id: "ibn-al-qayyim-bird",
        text: "The heart on its way to God is like a bird. Love is its head, and fear and hope are its two wings. When the head is sound the bird flies; when a wing fails, it does not.",
        attribution: "Ibn al-Qayyim",
        class: CLASSICAL,
        source: { work: MADARIJ, locator: "the chapter on love" },
        themes: ["fear-and-hope", "love-of-god", "the-heart", "hope"],
        confidence: "high",
    },
    {
        id: "ibn-al-qayyim-scattering",
        text: "In the heart there is a scattering that nothing gathers but turning to God, and a loneliness that nothing removes but keeping His company alone.",
        attribution: "Ibn al-Qayyim",
        class: CLASSICAL,
        source: { work: FAWAID, locator: "on the needs of the heart" },
        themes: ["the-heart", "remembrance-of-god", "love-of-god"],
        confidence: "high",
    },
    {
        id: "ibn-al-qayyim-sadness",
        text: "In the heart there is a sadness that nothing drives out but the gladness of knowing Him, and a restlessness that nothing settles but coming to rest in Him.",
        attribution: "Ibn al-Qayyim",
        class: CLASSICAL,
        source: { work: FAWAID, locator: "on the needs of the heart" },
        themes: ["the-heart", "remembrance-of-god", "contentment", "hope"],
        confidence: "high",
    },
    {
        id: "ibn-al-qayyim-repentance-beginning",
        text: "Repentance is the beginning of the servant's road, its middle and its end. He needs it at the end as much as he needed it at the start.",
        attribution: "Ibn al-Qayyim",
        class: CLASSICAL,
        source: { work: MADARIJ, locator: "the chapter on repentance" },
        themes: ["repentance", "purpose-of-life", "forgiveness"],
        confidence: "high",
    },
    {
        id: "ibn-al-qayyim-sound-heart",
        text: "A sound heart is one that is safe from any wanting that goes against what God commanded, and from any doubt that goes against what He said.",
        attribution: "Ibn al-Qayyim",
        class: CLASSICAL,
        source: { work: FAWAID, locator: "on the sound heart" },
        themes: ["the-heart", "sincerity", "honesty-and-truthfulness"],
        confidence: "high",
    },
    {
        id: "ibn-al-qayyim-wasting-time",
        text: "Wasting time is harder than death, because wasting time cuts you off from God and the life to come, while death cuts you off only from this world and the people in it.",
        attribution: "Ibn al-Qayyim",
        class: CLASSICAL,
        source: { work: FAWAID, locator: "on time" },
        themes: ["time-and-life", "purpose-of-life", "death-and-the-hereafter"],
        confidence: "high",
    },
    {
        id: "ibn-al-qayyim-gratitude-three",
        text: "Thankfulness shows in the heart as recognition, on the tongue as praise, and in the limbs as work done for the one who gave.",
        attribution: "Ibn al-Qayyim",
        class: CLASSICAL,
        source: { work: MADARIJ, locator: "the chapter on thankfulness" },
        themes: ["gratitude", "the-heart", "speech-and-the-tongue"],
        arabic: "شكر",
        confidence: "high",
    },
    {
        id: "ibn-al-qayyim-patience-three",
        text: "Patience is holding the self back from despair, holding the tongue back from complaint, and holding the hands back from striking out.",
        attribution: "Ibn al-Qayyim",
        class: CLASSICAL,
        source: { work: MADARIJ, locator: "the chapter on patience" },
        themes: ["patience-in-trials", "speech-and-the-tongue", "the-heart"],
        confidence: "high",
    },
    {
        id: "ibn-al-qayyim-door-of-humility",
        text: "When God wants good for a servant, He opens for him the door of feeling small and needy, and shuts on him the door of being pleased with himself.",
        attribution: "Ibn al-Qayyim",
        class: CLASSICAL,
        source: { work: FAWAID, locator: "on humility" },
        themes: ["humility", "guidance", "the-heart"],
        confidence: "medium",
    },
    {
        id: "ibn-al-qayyim-busy-with-himself",
        text: "The one who knows himself is busy mending himself rather than counting the faults of other people.",
        attribution: "Ibn al-Qayyim",
        class: CLASSICAL,
        source: { work: FAWAID, locator: "on knowing oneself" },
        themes: ["humility", "good-character", "community-and-brotherhood"],
        confidence: "medium",
    },
    {
        id: "ghazali-knowledge-without-action",
        text: "Knowledge without action is a kind of madness, and action without knowledge does not happen at all.",
        attribution: "Al-Ghazali",
        class: CLASSICAL,
        source: { work: AYYUHA, locator: "the opening counsel" },
        themes: ["knowledge", "sincerity", "guidance"],
        confidence: "high",
    },
    {
        id: "ghazali-how-many-nights",
        text: "How many nights have you spent turning over knowledge and reading books, keeping sleep away from yourself. I do not know what the purpose of it was.",
        attribution: "Al-Ghazali",
        class: CLASSICAL,
        source: { work: AYYUHA, locator: "the opening counsel" },
        themes: ["knowledge", "sincerity", "purpose-of-life"],
        confidence: "high",
    },
    {
        id: "ghazali-mirror-and-smoke",
        text: "The heart is a mirror, and the wrongs a person does are a smoke that settles on it, until in the end nothing at all is reflected there.",
        attribution: "Al-Ghazali",
        class: CLASSICAL,
        source: { work: IHYA, locator: "the Book of the Marvels of the Heart" },
        themes: ["the-heart", "repentance", "light"],
        confidence: "high",
    },
    {
        id: "ghazali-thankfulness-is-use",
        text: "Thankfulness is to use each thing you were given for the very purpose it was made for.",
        attribution: "Al-Ghazali",
        class: CLASSICAL,
        source: { work: IHYA, locator: "the Book of Patience and Thankfulness" },
        themes: ["gratitude", "purpose-of-life", "provision-and-sustenance"],
        confidence: "high",
    },
    {
        id: "ghazali-tongue-small-in-form",
        text: "The tongue is small in form, and the range of what it can do wrong is very wide.",
        attribution: "Al-Ghazali",
        class: CLASSICAL,
        source: { work: IHYA, locator: "the Book of the Faults of the Tongue" },
        themes: ["speech-and-the-tongue", "good-character"],
        confidence: "high",
    },
    {
        id: "ghazali-patience-is-half",
        text: "Patience is half of faith, and thankfulness is the other half, because everything that reaches you is either a favour to thank Him for or a trial to be patient with.",
        attribution: "Al-Ghazali",
        class: CLASSICAL,
        source: { work: IHYA, locator: "the Book of Patience and Thankfulness" },
        themes: ["patience-in-trials", "gratitude", "contentment"],
        confidence: "medium",
    },
    {
        id: "rumi-listen-to-the-reed",
        text: "Listen to the reed as it tells its story, complaining of separations. Ever since they cut me from the reed bed, men and women have wept at my cry.",
        attribution: "Rumi",
        class: CLASSICAL,
        source: { work: MASNAVI, locator: "Book I, the opening lines" },
        themes: ["love-of-god", "the-heart", "remembrance-of-god"],
        confidence: "high",
    },
    {
        id: "rumi-kept-far-from-the-root",
        text: "Everyone kept far from his own root looks again for the time when he was joined to it.",
        attribution: "Rumi",
        class: CLASSICAL,
        source: { work: MASNAVI, locator: "Book I, the opening lines" },
        themes: ["love-of-god", "purpose-of-life", "the-heart"],
        confidence: "high",
    },
    {
        id: "rumi-your-calling-was-my-answer",
        text: "A man grew tired of calling on God, since no answer ever came. In a dream he was told: your calling on Me was itself My answer to you.",
        attribution: "Rumi",
        class: CLASSICAL,
        source: { work: MASNAVI, locator: "Book III, the man who called on God" },
        themes: ["supplication", "hope", "remembrance-of-god"],
        confidence: "high",
    },
    {
        id: "rumi-one-thing-not-forgotten",
        text: "There is one thing in this world that must never be forgotten. Forget everything else and remember that, and nothing is lost; remember everything else and forget that, and nothing has been done.",
        attribution: "Rumi",
        class: CLASSICAL,
        source: { work: FIHI, locator: "Discourse 4" },
        themes: ["purpose-of-life", "remembrance-of-god"],
        confidence: "high",
    },
    {
        id: "rumi-moses-and-the-shepherd",
        text: "God said to Moses: I do not look at the tongue or at the words. I look at what is inside, and at the state the heart is in.",
        attribution: "Rumi",
        class: CLASSICAL,
        source: { work: MASNAVI, locator: "Book II, Moses and the shepherd" },
        themes: ["moses", "sincerity", "supplication", "the-heart"],
        confidence: "high",
    },
    {
        id: "rumi-elephant-in-the-dark",
        text: "Each of them put a hand on a different part of the elephant in the dark, and each described a different animal. Had there been a candle, the differences would have gone.",
        attribution: "Rumi",
        class: CLASSICAL,
        source: { work: MASNAVI, locator: "Book III, the elephant in the dark house" },
        themes: ["knowledge", "humility", "guidance", "light"],
        confidence: "high",
    },
    {
        id: "rumi-joseph-and-the-mirror",
        text: "A friend came to Joseph with empty hands. Asked for his gift, he held up a mirror: what should I bring the most beautiful of men, except something he can see himself in?",
        attribution: "Rumi",
        class: CLASSICAL,
        source: { work: MASNAVI, locator: "Book I, Joseph and the mirror" },
        themes: ["joseph", "sincerity", "the-heart"],
        confidence: "high",
    },
    {
        id: "rabia-burn-me-in-it",
        text: "God, if I worship You in fear of the Fire, burn me in it. If I worship You hoping for the Garden, shut me out of it. But if I worship You for Yourself, do not keep Your beauty from me.",
        attribution: "Rabia al-Adawiyya",
        class: CLASSICAL,
        source: { work: TADHKIRA, locator: "the chapter on Rabia al-Adawiyya" },
        themes: ["sincerity", "love-of-god", "worship-and-devotion", "fear-and-hope"],
        confidence: "high",
    },
    {
        id: "rabia-alone-with-you",
        text: "The stars are out, eyes are closed, kings have shut their doors, and every lover is alone with the one he loves. And here I am, alone with You.",
        attribution: "Rabia al-Adawiyya",
        class: CLASSICAL,
        source: { work: TADHKIRA, locator: "the chapter on Rabia al-Adawiyya" },
        themes: ["night-and-day", "love-of-god", "supplication"],
        confidence: "high",
    },
    {
        id: "rabia-because-i-love-him",
        text: "I have not served God out of fear of the Fire, nor for love of the Garden. I would be a poor servant if I had. I serve Him because I love Him.",
        attribution: "Rabia al-Adawiyya",
        class: CLASSICAL,
        source: { work: TADHKIRA, locator: "the chapter on Rabia al-Adawiyya" },
        themes: ["sincerity", "love-of-god", "worship-and-devotion"],
        confidence: "high",
    },
    {
        id: "ibn-hazm-knowledge-keeps-you-from-vanity",
        text: "If knowledge had no use except to keep you away from the vanity that makes fools happy, that alone would be reason enough to look for it.",
        attribution: "Ibn Hazm",
        class: CLASSICAL,
        source: { work: AKHLAQ, locator: "on knowledge" },
        themes: ["knowledge", "humility"],
        confidence: "medium",
    },
    {
        id: "ibn-hazm-busy-with-faults",
        text: "Whoever is busy with the faults of other people and forgetful of his own has a sickness he has not looked at.",
        attribution: "Ibn Hazm",
        class: CLASSICAL,
        source: { work: AKHLAQ, locator: "on character" },
        themes: ["good-character", "humility", "the-heart"],
        confidence: "medium",
    },

    // ── Companions and early generations, second pass ─────────────────────────────────
    {
        id: "ibn-masud-mountain-and-fly",
        text: "The believer sees his wrongs as though he sat under a mountain and feared it would fall on him. The careless man sees his wrongs as a fly that passed over his nose.",
        attribution: "Abdullah ibn Mas'ud",
        class: EARLY,
        source: { work: BUKHARI, locator: "6308" },
        themes: ["repentance", "fear-and-hope", "the-heart"],
        confidence: "high",
    },
    {
        id: "aisha-in-the-service-of-his-family",
        text: "She was asked what he did inside his house, and said: he was in the service of his family, and when the prayer came he went out to it.",
        attribution: "Aisha bint Abi Bakr",
        class: EARLY,
        source: { work: BUKHARI, locator: "676" },
        themes: ["family-and-parents", "good-character", "prayer", "humility"],
        confidence: "high",
    },
    {
        id: "aisha-never-struck-anything",
        text: "He never struck anything with his hand, not a servant and not a woman, except when he was fighting in the path of God.",
        attribution: "Aisha bint Abi Bakr",
        class: EARLY,
        source: { work: MUSLIM, locator: "2328" },
        themes: ["good-character", "mercy-of-god", "family-and-parents"],
        confidence: "high",
    },
    {
        id: "anas-ten-years",
        text: "I served him for ten years, and he never once said a harsh word to me, nor asked why I had done a thing, nor why I had not done it.",
        attribution: "Anas ibn Malik",
        class: EARLY,
        source: { work: BUKHARI, locator: "6038" },
        themes: ["good-character", "speech-and-the-tongue", "community-and-brotherhood"],
        confidence: "high",
    },
    {
        id: "ibn-sirin-whom-you-take-from",
        text: "This knowledge is religion, so look carefully at the people you take your religion from.",
        attribution: "Muhammad ibn Sirin",
        class: EARLY,
        source: { work: MUSLIM, locator: "the introduction" },
        themes: ["knowledge", "guidance", "honesty-and-truthfulness"],
        confidence: "high",
    },
    {
        id: "ibn-al-mubarak-the-chain",
        text: "The chain of transmission is part of the religion. Were it not for the chain, anyone at all would say whatever he liked.",
        attribution: "Abdullah ibn al-Mubarak",
        class: EARLY,
        source: { work: MUSLIM, locator: "the introduction" },
        themes: ["knowledge", "honesty-and-truthfulness", "revelation-and-its-rejection"],
        confidence: "high",
    },
    {
        id: "abu-bakr-whoever-used-to-worship",
        text: "Whoever used to worship Muhammad (peace be upon him), he has died. Whoever used to worship God, then God is living and does not die.",
        attribution: "Abu Bakr al-Siddiq",
        class: EARLY,
        source: { work: BUKHARI, locator: "3667" },
        themes: ["death-and-the-hereafter", "divine-attributes", "prophets"],
        confidence: "high",
    },
    {
        id: "abu-hurayra-on-an-empty-stomach",
        text: "People say that I narrate too much. I kept near the Prophet on an empty stomach while others were busy in the markets and on their land.",
        attribution: "Abu Hurayra",
        class: EARLY,
        source: { work: BUKHARI, locator: "118" },
        themes: ["knowledge", "contentment", "purpose-of-life"],
        confidence: "high",
    },
    {
        id: "ali-give-a-little",
        text: "Do not be ashamed to give a little, for turning someone away with nothing is smaller still.",
        attribution: "Ali ibn Abi Talib",
        class: EARLY,
        source: { work: NAHJ, locator: "Short Sayings" },
        themes: ["charity", "greed-and-generosity", "humility"],
        confidence: "high",
    },
];
